wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1663771939.10814
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.10.4
      5: 0.13.3
      8:
      - 3
      - 5
    visualize:
      my_custom_id:
        panel_config:
          fieldSettings:
            lineKey: lineKey
            lineVal: lineVal
            step: step
          panelDefId: wandb/lineseries/v0
          stringSettings:
            title: Train/Test Accuracy
            xname: epoch
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: my_custom_id_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
